name: CI
on:
  push:
    branches: [ci]
  workflow_dispatch:

jobs:
  build:
    name: Build via Cabal
    runs-on: ubuntu-22.04
    # strategy:
    #   fail-fast: true
    #   matrix:
    #     ghc-ver:
    #       - 9.10
    #       - 9.12
    #       - 9.14
    env:
      GHC_VER: ${ matrix.ghc-ver }

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup cache
        uses: actions/cache@v6
        with:
          path: ~/.ghc-wasm
          key: ghc-wasm-${{ runner.os }}

      - name: Setup ghcup
        uses: haskell/ghcup-setup@v1

      - name: Setup Haskell WASM
        run: |
          GHC_WASM_META_COMMIT_HASH=60098a5076557e327b326a1a3ba3b5fb4fec1e49
          git clone https://gitlab.haskell.org/ghc/ghc-wasm-meta.git --revision=$GHC_WASM_META_COMMIT_HASH --depth=1
          cd ghc-wasm-meta/
          export SKIP_GHC=yes
          ./setup.sh
          source ~/.ghc-wasm/env
          cd ..

          ghcup config add-release-channel https://gitlab.haskell.org/haskell-wasm/ghc-wasm-meta/-/raw/$GHC_WASM_META_COMMIT_HASH/ghcup-wasm-0.0.9.yaml
          echo "Fetching ghc versions..."
          GHC_WASM_ID=$(ghcup list -t ghc -r | grep wasm32-wasi-9.10 | tail -n1 | cut -d" " -f2)
          echo "Will install $GHC_WASM_ID"
          ghcup install ghc "$GHC_WASM_ID" -- --host=x86_64-linux --with-intree-gmp --with-system-libffi && true
          cat /usr/local/.ghcup/logs/*

      - name: Build
        run: |
          ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build
          path: |
            hs-lsp-reactor.wasm
            jsffi.js
